### ISSUE TITLE
Unable to install in Magento 2.0.4

### ISSUE THREAD

**Issue by chrisss404** [wirecard/magento2-epp#1]
I need guidance on how to I install this extension. My attempt ended with a PHP Fatal error, see subsequent steps. Maybe I got something wrong...

First I added the extension as dependency to composer.json

    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        {
            "type": "vcs",
            "url": "https://github.com/wirecard/magento2-epp"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.4",
        "composer/composer": "@alpha",
        "magento/module-bundle-sample-data": "^100.0",
        "wirecard/magento2-epp": "dev-master"
    },
    "minimum-stability": "dev",

Then I updated my dependencies by:

    $ composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)          
    Package operations: 8 installs, 0 updates, 0 removals
      - Installing robrichards/xmlseclibs (2.0.1): Loading from cache
      - Installing myclabs/php-enum (1.5.1): Downloading (100%)         
      - Installing psr/http-message (1.0.1): Downloading (100%)         
      - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)         
      - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)         
      - Installing guzzlehttp/guzzle (6.2.3): Downloading (100%)         
      - Installing wirecard/payment-sdk-php (dev-master e046f57): Cloning e046f57b47
      - Installing wirecard/magento2-epp (dev-master 227153d): Cloning 227153da46
    robrichards/xmlseclibs suggests installing ext/openssl (OpenSSL extension)
    robrichards/xmlseclibs suggests installing ext/mcrypt (MCrypt extension)
    Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
    Writing lock file
    Generating autoload files

And when I try to activate the extension, I get the following error:

    $ php bin/magento setup:upgrade
    Cache cleared successfully
    File system cleanup:
    /var/www/html/var/generation/Composer
    /var/www/html/var/generation/Magento
    /var/www/html/var/generation/Symfony
    The directory '/var/www/html/var/di/' doesn't exist - skipping cleanup
    Updating modules:
    PHP Fatal error:  Interface 'Magento\Payment\Gateway\ConfigFactoryInterface' not found in /var/www/html/vendor/wirecard/magento2-epp/Config/PaymentSdkConfigFactory.php on line 45

Best regards & thanks in advance

**Comment by michaldrozd** [comment]
Hello Chriss. I will check it. Michal

**Comment by michaldrozd** [comment]
Please do following:
Edit `composer.json` and change `minimum-stability` to "dev"
Add custom VCS repository, as you already did.
And finally just run
`composer require wirecard/magento2-epp @dev`

And it should be working.

**Comment by chrisss404** [comment]
I followed your steps and the fatal error did not occur any more.

However it seems that the plugin gets not enabled. Here is a screenshot of the payment method configuration page showing all available methods:
![magento2 configuration](https://cloud.githubusercontent.com/assets/980871/25755404/3ad1faf2-31c3-11e7-8551-73854850c687.png)

Additionally when I run the module status command, it returns the following

    $ php bin/magento module:status
    List of enabled modules:
    Magento_Store
    Magento_AdvancedPricingImportExport
    Magento_Directory
    ...
    Magento_BundleSampleData
    Magento_CatalogWidget
    Magento_Wishlist
    
    List of disabled modules:
    Wirecard_EPP

According to the [docs](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-enable.html) it seems that I have to run the `setup:upgrade` command, which causes the issue, at some point in order to enable the module. Is this correct?

Meanwhile, I looked around a little and found that there are more Magento2 plugins by Wirecard:

* magento2-epp
* magento2-ee
* magento2-wcp
* magento2-wcs

I figured that `magento2-wcp` and `magento2-wcs` use different endpoints compared to this extension, but it looks like that `magento2-epp` and `magento2-ee` use the same endpoint, so I was wondering which one to use? Can you please give me some insights.

Best regards and thanks for getting back to me so quickly.

**Comment by michaldrozd** [comment]
yes, after `composer require wirecard/magento2-epp @dev` you must run standard magento commands:
```
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```
and then this module should be active.

Extension magento2-epp is OK, it is extension you need. `magento2-ee` is just under development extension for REST Paypal. Extensions `magento2-wcp` and `magento2-wcs` are completely different extensions for another ("legacy") payment gateway.

**Comment by chrisss404** [comment]
Unfortunately no success, now I get the previously described error:

    $ php bin/magento setup:upgrade
    Cache cleared successfully
    File system cleanup:
    /var/www/html/var/generation/Composer
    /var/www/html/var/generation/Magento
    /var/www/html/var/generation/Symfony
    The directory '/var/www/html/var/di/' doesn't exist - skipping cleanup
    Updating modules:
    PHP Fatal error:  Interface 'Magento\Payment\Gateway\ConfigFactoryInterface' not found in /var/www/html/vendor/wirecard/magento2-epp/Config/PaymentSdkConfigFactory.php on line 45

I was a little confused about all the plugins, thanks for letting me know.

Maybe I'll try again later with Magento 2.1.

**Comment by michaldrozd** [comment]
maybe it is permission issue so you could double check if you have 777 on `var` and `pub` directories (if working under linux)

**Comment by chrisss404** [comment]
Yes, I use Linux. I just tried your suggestion, but still the same issue:

    $ chmod -R 0777 pub
    $ chmod -R 0777 var
    $ php bin/magento setup:upgrade
    PHP Fatal error:  Interface 'Magento\Payment\Gateway\ConfigFactoryInterface' not found in /var/www/html/vendor/wirecard/magento2-epp/Config/PaymentSdkConfigFactory.php on line 45

**Comment by michaldrozd** [comment]
Ok, you are right. installation failed for version 2.0.x. i just tried it.
I primary tested it for magento 2.1.x. I will check what is wrong with 2.0

**Comment by michaldrozd** [comment]
Chriss it should be working now. It was simple fix (removing interface implementation)

**Comment by chrisss404** [comment]
k, thx
